### ISSUE TITLE
Refacto fiche produit

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#103]
Une fois qu'on a validé que le concept fonctionne bien sur les membres

```[tasklist]
### Tasks
- [x] Refacto la gestion de la fiche produit avec zod+react-hook-form : https://github.com/betagouv/espace-membre-next/pull/189
- [x] Reuse de la PR : https://github.com/betagouv/espace-membre-next/pull/140
- [ ] https://github.com/betagouv/espace-membre-next/issues/57
- [ ] https://github.com/betagouv/animation-communaute/issues/28
- [ ] https://github.com/betagouv/beta.gouv.fr/issues/4509
- [ ] pouvoir mettre plusieurs repos pour la SE
- [ ] https://github.com/betagouv/espace-membre-next/issues/39
- [ ] https://github.com/betagouv/espace-membre-next/issues/149
- [x] Ajout de sponsors semble HS (modal ne s'ouvre pas)
```
