### ISSUE TITLE
lister les features netlify-cms à reintégrer dans espace-membre

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#49]
En prévision de la suppression de netlify 
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/espace-membre-next/issues/60
- [ ] https://github.com/betagouv/espace-membre-next/issues/62
- [ ] https://github.com/betagouv/espace-membre-next/issues/63
- [ ] https://github.com/betagouv/espace-membre-next/issues/64
```
