### ISSUE TITLE
create/edit fiche produit : champs manquants

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#57]
```[tasklist]
### Tasks
- [ ] soumis au DSFR ou pas
- [x] url page budget
- [ ] site web optionnel (ex: app mobile ou privée)
```
